# Generated by Django 5.0.6 on 2024-07-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
