# Generated by Django 5.0.6 on 2024-08-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_alter_socio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='baja',
            field=models.BooleanField(default=False),
        ),
    ]
